<?php

namespace Slackiss\Bundle\SocialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function getQueryByRole($role){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
           ->from($this->_entityName, 'u')
           ->where('u.roles LIKE :roles')
           ->setParameter('roles', '%' . $role . '%');
        return $qb->getQuery();
    }

}
