<?php

namespace Slackiss\Bundle\SocialBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MemberProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberProfileRepository extends EntityRepository
{
}
