# app/config/security.yml
security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        main:
            pattern: ^/*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me:    true
                default_target_path: /
                check_path: /login_check
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true

    access_control:
        - { path: ^/avid/login$,                 role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,                   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,                    role: ROLE_NONE }
        - { path: ^/profile,                     role: ROLE_USER }
        - { path: ^/account,                     role: ROLE_USER }
        - { path: ^/social,                      role: ROLE_USER}
        - { path: ^/admin,                       role: ROLE_ADMIN }
